v = input('Digite algo: ')
print(f'O tipo primitivo da variável é {type(v)}.')
print(f'É alfanumérico? {v.isalnum()}')
print(f'Só tem espaços? {v.isspace()}')
print(f'Só tem números? {v.isnumeric()}')
print(f'É alfanumérico? {v.isalpha()}')
print(f'Tá em maiúsculo? {v.isupper()}')
print(f'Tá em minúsculo? {v.islower()}')
print(f'Está capitalizada? {v.istitle()}')
