frase = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
frase2 = frase.upper()
frase3 = frase.lower()
print(f'Seu nome em letras maísculas é {frase2}.')
print(f'Seu nome em letras minúsculas é {frase3}.')
espac = frase.count(' ')
print(f'Seu nome tem {len(frase)-espac} letras.')
frase4 = frase.split()
print(f'Seu primeiro nome é {frase4[0]} e ele tem {len(frase4[0])} letras.')
