n1 = int(input('Digite o primeiro valor: '))
n2 = int(input('Digite o segundo valor: '))
n3 = int(input('Digite o terceiro valor: '))
maior = max(n1, n2, n3)
menor = min(n1, n2, n3)
print(f'O maior valor é {maior}.')
print(f'O menor valor é {menor}.')
